name: Calificación automática

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Otter-Grader
        run: pip install otter-grader

      - name: Ejecutar calificación automática
        run: otter grade

      - name: Mostrar archivos de calificación
        run: ls -R otter-grader
